version: '1.0'
stages:
  - clone
  - build
  - deploy
steps:
  ClonePackerRepository:
    title: Cloning Packer repository...
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: github
    revision: ${{CF_REVISION}}
    stage: clone   
  CreatePackerImage:
    title: Creating AMI...
    image: dustinvanbuskirk/packer-ansible:1.6.0-2.9.7-r0
    working_directory: ${{ClonePackerRepository}}
    commands:
      - packer validate packer.json
      - packer build -var 'aws_access_key=${{AWS_ACCESS_KEY_ID}}' -var 'aws_secret_key=${{AWS_SECRET_ACCESS_KEY}}' packer.json
      - cf_export AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
    stage: build
  RunTerraformPlan:
    title: Running Terraform Plan
    image: alpine
    working_directory: ${{ClonePackerRepository}}
    commands:
      - echo "Building EC2 instance with AMI:$AMI_ID"
    stage: deploy